### ISSUE TITLE
Feature request: Author info in blog post meta data

### ISSUE THREAD

**Issue by awfrancisco** [18F/beta.18f.gov#2]
> @18F any chance you could start putting author info in the meta tags of blog posts? Would be super useful for citation mgmt apps!

https://twitter.com/sheepeeh/status/713384540668952577

**Comment by maya** [comment]
Added date, author, and tags in: https://github.com/18F/beta.18f.gov/pull/9/files#diff-e921a390257abd15c1742300f2417b13R30.
