### ISSUE TITLE
508 Issues

### ISSUE THREAD

**Issue by nickbristow** [18F/beta.18f.gov#29]
From 7/29/16 review
see google drive/18f/508/reviews
- [x] Focus rect is missing from 18f logo at top of page
- [x] Continue reading links should have aria description or hidden text indicating which article they refer to
- [x] Footer headers skip a level throwing off document outline

**Comment by maya** [comment]
For #3, the footer h5 should be an h2.

**Comment by elainekamlley** [comment]
@msecret ready to get started on theses tomorrow :)

**Comment by maya** [comment]
Fixed in #34 and #30.
