### ISSUE TITLE
Add site description for link sharing

### ISSUE THREAD

**Issue by maya** [18F/beta.18f.gov#35]
When I post a link to the home page on Slack I get:

> 18F: Digital service delivery | Home
> A fresh start for 18f.gsa.gov 

Maybe "A fresh start for 18f.gsa.gov" should be something else?

This is what it looks like:

<img width="487" alt="screen shot 2016-08-16 at 12 59 52 pm" src="https://cloud.githubusercontent.com/assets/5249443/17713816/b364b436-63b1-11e6-91dc-d534856dc397.png">

cc: @gboone @elainekamlley @awfrancisco

**Comment by maya** [comment]
Actually it's happening on all pages that are not a blog post:

<img width="792" alt="screen shot 2016-08-16 at 1 08 07 pm" src="https://cloud.githubusercontent.com/assets/5249443/17713993/8d1cdd3e-63b2-11e6-8e14-63df4b5832cd.png">

**Comment by maya** [comment]
Here's the code that does this:

```
{% if page.description %}
  <meta name="description" content="{{ page.description | xml_escape }}">
  <meta property="og:description" content="{{ page.description | xml_escape }}" />
{% else %}
  <meta name="description" content="{{ site.description | xml_escape }}">
  <meta property="og:description" content="{{ site.description | xml_escape }}" />
{% endif %}
```

Looks like we need two things:
- [x] A better site-wide description
- [ ] A description for each page (if we don't want to use the site-wide one)

**Comment by gboone** [comment]
This is what we use on 18f.gsa.gov right now if there's nothing specified in the `page.description` 

> "18F builds effective, user-centric digital services focused on the interaction between government and the people and businesses it serves."

**Comment by maya** [comment]
@gboone added in https://github.com/18F/beta.18f.gov/pull/36/commits/6afa3d778356f8b5266aee51cc49a1b8f1e623fd
