### ISSUE TITLE
Consolidate layouts

### ISSUE THREAD

**Issue by hbillings** [18F/beta.18f.gov#8]
From @maya: "The only difference [between the layouts] is one has a grid around the content and the other does not. We could remove the grid one and add it manually for each page. But the advantage of having grid in the template is the page content can be pure markdown and easier for people to update and add new pages."

Possibly we could add grids in selectively if they are not pages of a type that should be gridless?

**Comment by maya** [comment]
Removed `default-grid.html` in #14.
